### ISSUE TITLE
[Question] Assistance with Jenkins/CLI integration

### ISSUE THREAD

**Issue by SRandazzo** [codecov/example-swift#2]
Hey, Thanks for such a great tool!

I've been following along on https://github.com/venmo/slather/pull/99 and am curious how to get up and running with CodeCov/Obj-C + Swift reports on some private repositories.

We are not using Travis, and I haven't been able to find a good step by step on how I can hook this all up via command line scripts. We currently run everything through a simple Jenkins job, which just executes some testing.sh scripts. I have code coverage data generating via xcode.

 Any chance you can help us out, would love to get our organization setup!
Thanks!

**Comment by stevepeak** [comment]
Awesome! We have two uploading tools that work with Swift: a [Bash](https://github.com/codecov/codecov-bash) and [Python](https://github.com/codecov/codecov-python). You are welcome to give these a try by adding them to your Jenkins build, in your `testing.sh` file.

```sh
# via bash
bash <(curl -s https://codecov.io/bash)
# (or) via python
pip install --user codecov && codecov
```

I'm happy to provide more help if you would like. Since it is a private repository you can contact me directly at [steve@codecov.io](mailto:steve@codecov.io). Thank you!

**Comment by SRandazzo** [comment]
Marking as resolved thanks help from @stevepeak The above worked and was super easy!
